export const metadata = {
  title: "Terms of Use",
  description: "Terms of Use for ToolName.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <h1 className="text-4xl font-bold">Terms of Use</h1>

      <div className="mt-8 space-y-8 leading-7 text-gray-600">
        <p>
          By accessing and using ToolName, you agree to these Terms of Use.
          If you do not agree with these terms, please do not use the website.
        </p>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Use of Our Tools
          </h2>

          <p className="mt-3">
            Our tools are provided for general informational and practical
            purposes. You are responsible for how you use the results
            generated by our tools.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Acceptable Use
          </h2>

          <p className="mt-3">
            You agree not to misuse the website, attempt to interfere with its
            operation, or use our services for unlawful purposes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Accuracy of Information
          </h2>

          <p className="mt-3">
            We make reasonable efforts to provide useful and accurate tools,
            but we do not guarantee that all results will always be complete,
            accurate, or suitable for a particular purpose.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Availability
          </h2>

          <p className="mt-3">
            We may modify, suspend, or discontinue any part of the website or
            its tools at any time without prior notice.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Intellectual Property
          </h2>

          <p className="mt-3">
            Unless otherwise stated, the website design, branding, original
            content, and software are owned by or licensed to ToolName.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Limitation of Liability
          </h2>

          <p className="mt-3">
            To the extent permitted by applicable law, ToolName is not
            responsible for losses or damages resulting from the use of or
            reliance on the website or its tools.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Changes to These Terms
          </h2>

          <p className="mt-3">
            We may update these Terms of Use from time to time. Continued use
            of the website after changes are published constitutes acceptance
            of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900">
            Contact
          </h2>

          <p className="mt-3">
            If you have questions about these terms, please contact us through
            our Contact page.
          </p>
        </section>
      </div>
    </main>
  );
}